### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by mkayys** [mkayys/InTents#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by ryan-mapa** [comment]
[ ] - Can't seem to sign up a new user
[ ] - Can't scroll to bottom of sign up when errors are rendered
[ ] - Save sign up form state so user does not have to restart on accidental modal close

**Comment by ryan-mapa** [comment]
Well done!
